# Generated by Django 5.1.1 on 2024-10-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='enlace',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='tecnologias',
            new_name='technologies',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='titulo',
            new_name='title',
        ),
    ]
