# Generated by Django 5.1.1 on 2024-10-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_fecha_proyecto_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Project',
        ),
    ]
